# -*- coding: utf-8 -*-
"""Generated by ArcGIS ModelBuilder on: 2019-12-23 13:52:41
All ModelBuilder functionality may not be exported. Edits may be required for equivalency with the original model.
"""

import arcpy
import os

# To allow overwriting the outputs change the overwrite option to true.
arcpy.env.overwriteOutput = False

# Script parameters
arcpy.env.workspace = arcpy.GetParameterAsText(0)

# Local variables:
# db_path = r"C:\Users\dstarr\Documents\ArcGIS\Projects\PortofCleveland"
# dataset_path = r"C:\Users\dstarr\Documents\ArcGIS\Projects\PortofCleveland/"+arcpy.env.workspace
datasets = arcpy.ListDatasets(feature_type='feature')
datasets = [''] + datasets if datasets is not None else []
arcpy.AddMessage("Create Attribute Rules for All Feature Classes")

for ds in datasets:
    for fc in arcpy.ListFeatureClasses(feature_dataset=ds):
        path = os.path.join(arcpy.env.workspace, ds, fc)
        arcpy.AddMessage(path)
        at_message = "Add Attribute Rules -- " + path
        arcpy.AddMessage(at_message)

        # Process: Add Attribute Rule
        arcpy.AlterAttributeRule_management(in_table=path, name="UniqueID", description="", error_number="", error_message="", tags="", triggering_events="INSERT;UPDATE;DELETE", script_expression="$feature.DATASET_TYPE + $feature.FEATURE_TYPE + Text(Now(), 'YMDSSS') +Text($feature.OBJECTID, '000');")

# Process: Create Attribute Rules for All Feature Classes

# for fc_array_layers, geometry_array_list in zip(featureClass_array_split2, geometry_array_split2):
#
#
#     fc = arcpy.env.workspace+"/"+fc_array_layers
#
#
#




